urls.py
from django.conf.urls import url

from . import views


app_name = 'activities'
urlpatterns = [
    url(r'^(angebot/)?$', views.ActivityList.as_view(), name="activity-list"),
    url(r'^angebot/(?P<pk>[0-9]+)/$', views.ActivityDetail.as_view(), name='activity-detail'),
    url(r'^bildungsbereich/$', views.FieldOfEducationList.as_view(), name="foe-list"),
    url(r'^bildungsbereich/(?P<pk>[0-9]+)/$', views.FieldOfEducationDetail.as_view(), name="foe-detail"),
    url(r'^material/$', views.MaterialList.as_view(), name="material-list"),
    url(r'^material/(?P<pk>[0-9]+)/$', views.MaterialDetail.as_view(), name="material-detail"),
    url(r'^jahreszeit/$', views.SeasonList.as_view(), name="season-list"),
    url(r'^jahreszeit/(?P<pk>[FSHW])/$', views.SeasonDetail.as_view(), name="season-detail"),
    url(r'^tag/$', views.TagList.as_view(), name="tag-list"),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagDetail.as_view(), name="tag-detail"),
    url(r'^fest/$', views.FestivalList.as_view(), name="festival-list"),
    url(r'^fest/(?P<pk>[0-9]+)/$', views.FestivalDetail.as_view(), name="festival-detail"),
]

models.py
import os

from django.db import models
from django.core.validators import MaxValueValidator, RegexValidator

from .templatetags.activity_extras import RE_HASHTAG


def file_upload_path(instance, filename):
    last_file = instance.__class__.objects.order_by("-id").first()
    file_id = 1 if last_file is None else last_file.id + 1
    ext = os.path.splitext(filename)[1]
    classname = instance.__class__.__name__.lower()
    return "activity{}/{}{}{}".format(instance.activity_id, classname, file_id, ext)


class FieldOfEducation(models.Model):
    name = models.CharField(max_length=50, unique=True,
                            help_text="Maximal 50 Zeichen.",
                            verbose_name="Bildungsbereich")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Bildungsbereich"
        verbose_name_plural = "Bildungsbereiche"


class Material(models.Model):
    name = models.CharField(max_length=250, unique=True,
                            help_text="Maximal 250 Zeichen. Mehrzahl verwenden.",
                            verbose_name="Material")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Materialien"


class Season(models.Model):
    SPRING = 'F'
    SUMMER = 'S'
    AUTUMN = 'H'
    WINTER = 'W'
    SEASON_CHOICES = (
        (SPRING, "Frühling"),
        (SUMMER, "Sommer"),
        (AUTUMN, "Herbst"),
        (WINTER, "Winter"))
    name = models.CharField(max_length=1, choices=SEASON_CHOICES, primary_key=True,
                            verbose_name="Kürzel Jahreszeit")
    full_name = models.CharField(max_length=8, unique=True,
                                 verbose_name="Jahreszeit")

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "Jahreszeit"
        verbose_name_plural = "Jahreszeiten"


class Festival(models.Model):
    name = models.CharField(max_length=250, unique=True,
                            help_text="Maximal 50 Zeichen.",
                            verbose_name="Fest")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Fest"
        verbose_name_plural = "Feste"


class Tag(models.Model):
    # Match if there is a non-letter at the beginning or end of the word.
    tag_validator = RegexValidator(r"""\W+|\w+\W+""", inverse_match=True)
    name = models.CharField(max_length=50, unique=True, editable=False,
                            validators=[tag_validator],
                            help_text="Maximal 50 Zeichen.")

    def __str__(self):
        return self.name


class Activity(models.Model):
    ACTIVITY_CHOICES = (
        (None, "Egal"),
        (True, "Drinnen"),
        (False, "Draußen"))
    maximum_default = 99
    max_validator = MaxValueValidator(maximum_default)

    title = models.CharField(max_length=250, unique=True,
                             help_text="Maximal 250 Zeichen.",
                             verbose_name="Titel")
    min_age = models.PositiveSmallIntegerField(
                default=0, validators=[max_validator],
                help_text="Alter muss zwischen 0 und 99 liegen.",
                verbose_name="Mindestalter")
    max_age = models.PositiveSmallIntegerField(
                default=maximum_default, validators=[max_validator],
                help_text="Alter muss zwischen 0 und 99 liegen.",
                verbose_name="Maximalalter")
    groupsize_min = models.PositiveSmallIntegerField(
                default=0, validators=[max_validator],
                help_text="Gruppengröße muss zwischen 0 und 99 liegen.",
                verbose_name="minimale Gruppengröße")
    groupsize_max = models.PositiveSmallIntegerField(
                default=maximum_default, validators=[max_validator],
                help_text="Gruppengröße muss zwischen 0 und 99 liegen.",
                verbose_name="maximale Gruppengröße")
    source = models.CharField(max_length=2000, blank=True,
                              help_text="z.B. URL einer Website, Titel und Seites eines Buchs…",
                              verbose_name="Quelle")
    description = models.TextField(help_text="Ausführliche Angebotsbeschreibung.",
                                   verbose_name="Durchführung")
    setting = models.NullBooleanField(choices=ACTIVITY_CHOICES, default=None,
                                help_text=("Die Standardeinstellung ist für Angebote, "
                                           "die sowohl drinnen als auch draußen durchführbar sind."),
                                verbose_name="Umgebung")
    seasons = models.ManyToManyField(Season,
                                     help_text=("Zu welchen Jahreszeiten passt das Angebot? "
                                                "Ist die Jahreszeit egal, bitte alle auswählen."),
                                     verbose_name="Jahreszeiten")
    tags = models.ManyToManyField(Tag, blank=True,
                                  help_text=("Für beliebige Stichworte mit je Maximallänge 50. "
                                             "Tags werden direkt in der Beschreibung mittels "
                                             "vorangestelltem # zugefügt."))
    materials = models.ManyToManyField(Material, through="MaterialAmount", blank=True,
                                       help_text=("Welche Materialien sind notwendig? "
                                                  "Mengenangaben sind optional."),
                                       verbose_name="Materialien")
    field_of_education = models.ManyToManyField(FieldOfEducation,
                            help_text="Bildungs- und Erziehungsbereiche, die betroffen sind.",
                            verbose_name="Bildungsbereiche")
    festivals = models.ManyToManyField(Festival, blank=True,
                                       help_text="Hier die Feste angeben, falls das Angebot diese betrifft.",
                                       verbose_name="Feste")

    def update_tags_from_description(self):
        """
        Search description for hashtags, remove obsolete tags and add new tags
        if necessary.
        """
        new_tags = set(match.group(2).lower() for match in RE_HASHTAG.finditer(self.description))
        self.tags.exclude(name__in=new_tags).delete()  # Delete obsolete tags.
        existing_tags = Tag.objects.filter(name__in=new_tags)
        existing_tag_names = set(tag.name for tag in existing_tags)
        new_tags = filter(lambda x: x not in existing_tag_names, new_tags)
        new_tags = tuple(Tag.objects.create(name=tag) for tag in new_tags)
        self.tags.add(*new_tags, *existing_tags)

    def save(self, *args, **kwargs):
        """
        Parse tags from description and save them as well as its relations.
        """
        super(Activity, self).save(*args, **kwargs)
        self.update_tags_from_description()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Angebot"
        verbose_name_plural = "Angebote"


class Image(models.Model):
    
    description = models.CharField(max_length=250, blank=True,
                                   help_text="Optional: Kurze Beschreibung mit Maximallänge 250.",
                                   verbose_name="Beschreibung")
    upload = models.ImageField(upload_to=file_upload_path)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE,
                                 verbose_name="Angebot")

    def __str__(self):
        return self.upload.url

    class Meta:
        verbose_name = "Bild"
        verbose_name_plural = "Bilder"


class File(models.Model):
    description = models.CharField(max_length=250, blank=True,
                                   help_text="Optional: Kurze Beschreibung mit Maximallänge 250.",
                                   verbose_name="Beschreibung")
    upload = models.FileField(upload_to=file_upload_path)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE,
                                 verbose_name="Angebot")

    def __str__(self):
        return self.upload.url

    class Meta:
        verbose_name = "Dateianhang"
        verbose_name_plural = "Dateianhänge"


class MaterialAmount(models.Model):
    UNIT_CHOICES = (
        ("", ""),
        ("l", "l"),
        ("ml", "ml"),
        ("g", "g"),
        ("mg", "mg"),
        ("Ta", "Tassen"),
        ("EL", "EL"),
        ("TL", "TL"),
        ("St", "Stück"))
    UNIT_DICT = dict(UNIT_CHOICES)

    material = models.ForeignKey(Material, on_delete=models.PROTECT,
                                 verbose_name="Material")
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE,
                                 verbose_name="Angebot")
    amount = models.PositiveIntegerField(default=0,
                                         help_text="Auf 0 lassen falls keine präzise Mengenangabe nötig.",
                                         verbose_name="Menge")
    unit = models.CharField(max_length=2, choices=UNIT_CHOICES, blank=True, default="",
                            help_text="Optional. Falls eine Maßeinheit fehlt bitte beim Administrator melden.",
                            verbose_name="Maßeinheit")
    per_child = models.BooleanField(default=False,
                                    help_text="Gesamtmenge oder Menge je Kind?",
                                    verbose_name="je Kind")

    def __str__(self):
        if self.amount == 0:
            return str(self.material)
        else:
            return "{} {} {}{}".format(self.amount, self.UNIT_DICT[self.unit], self.material,
                                        " je Kind" if self.per_child else "")

    class Meta:
        verbose_name = "Material und Mengen"
        verbose_name_plural = "Materialien und Mengen"

templates/activities/activity_detail.html
{% extends "activities/base.html" %}
{% load activity_extras %}

{% block title %}Angebot – {{ object.title }}{% endblock %}
{% block headline %}{{ object.title }}{% endblock %}

{% block content %}
<img src="{{ object.image_set.first }}" alt="{{ object.image_set.first.description }}" class="pure-img" />
<p><b>Alter:</b> {{ object.min_age }}{% if object.max_age == 99 %}+{% else %} bis {{ object.max_age}}{% endif %}</p>
<p><b>Bildungsbereiche:</b> {{ object.field_of_education.all|join:", " }}</p>
<p><b>Materialien:</b>
<ul>{{ object.materialamount_set.all|unordered_list }}</ul>
</p>
<p><b>Jahreszeiten:</b> {{ object.seasons.all|join:", " }}</p>
<p><b>Feste:</b> {{ object.festivals.all|join:", " }}</p>
<p><b>Aktivität:</b> {{ object.setting|yesno:"Drinnen,Draußen,Drinnen und Draußen" }}</p>
<p>{{ object.description|hashtagger|linebreaks }}</p>
<p><b>Dateianhänge:</b>
<ul>
{% for file in object.file_set.all %}<li><a href="{{ file }}">{{ file.upload.name }}</a></li>{% endfor %}
</ul>
</p>
{% endblock %}

templates/activities/activity_list.html
{% extends "activities/base.html" %}

{% block title %}Angebotsübersicht{% endblock %}
{% block headline %}Angebotsübersicht{% endblock %}

{% block content %}
<ul>
{% for object in object_list %}
   <li><a href="{% url 'activities:activity-detail' object.id %}">{{ object.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/base.html
{% load static %}

<!DOCTYPE html>
<html lang="de">
<head>
	<meta charset="UTF-8">
	<meta name="robots" content="noindex, nofollow">
    <link rel="stylesheet" type="text/css" href="{% static 'activities/pure.css' %}">
	<title>Erzieherdatenbank – {% block title %}Startseite{% endblock %}</title>
</head>
<body>
	<div id="headerbar" class="pure-menu pure-menu-horizontal">
	   {% block headerbar %}
	   <a href="{% url 'activities:activity-list' %}">Angebote</a> – 
	   <a href="{% url 'activities:foe-list' %}">Bildungsbereiche</a> – 
	   <a href="{% url 'activities:season-list' %}">Jahreszeiten</a> –
       <a href="{% url 'activities:festival-list' %}">Feste</a> –
	   <a href="{% url 'activities:material-list' %}">Materialien</a> – 
	   <a href="{% url 'activities:tag-list' %}">Tags</a> –
       <a href="{% url 'admin:index' %}">Redaktion</a>
	   {% endblock %}
	</div>
	<div id="content">
	    <h1>{% block headline %}Startseite{% endblock %}</h1>
	    {% block content %}{% endblock %}
	</div>
</body>
</html>

templates/activities/festival_detail.html
{% extends "activities/base.html" %}

{% block title %}Fest – {{ object.name }}{% endblock %}
{% block headline %}Fest: {{ object.name }}{% endblock %}

{% block content %}
<ul>
{% for object in object.activity_set.all %}
   <li><a href="{% url 'activities:activity-detail' object.id %}">{{ object.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/festival_list.html
{% extends "activities/base.html" %}

{% block title %}Feste{% endblock %}
{% block headline %}Feste{% endblock %}

{% block content %}
<ul>
{% for object in object_list %}
   <li><a href="{% url 'activities:festival-detail' object.id %}">{{ object.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/fieldofeducation_detail.html
{% extends "activities/base.html" %}

{% block title %}Bildungsbereich – {{ object.name }}{% endblock %}
{% block headline %}Bildungsbereich: {{ object.name }}{% endblock %}

{% block content %}
<ul>
{% for object in object.activity_set.all %}
   <li><a href="{% url 'activities:activity-detail' object.id %}">{{ object.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/fieldofeducation_list.html
{% extends "activities/base.html" %}

{% block title %}Bildungsbereiche{% endblock %}
{% block headline %}Bildungsbereiche{% endblock %}

{% block content %}
<ul>
{% for object in object_list %}
   <li><a href="{% url 'activities:foe-detail' object.id %}">{{ object.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/material_detail.html
{% extends "activities/base.html" %}

{% block title %}Material – {{ object.name }}{% endblock %}
{% block headline %}Material: {{ object.name }}{% endblock %}

{% block content %}
<ul>
{% for object in object.activity_set.all %}
   <li><a href="{% url 'activities:activity-detail' object.id %}">{{ object.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/material_list.html
{% extends "activities/base.html" %}

{% block title %}Materialien{% endblock %}
{% block headline %}Materialien{% endblock %}

{% block content %}
<ul>
{% for object in object_list %}
   <li><a href="{% url 'activities:material-detail' object.id %}">{{ object.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/season_detail.html
{% extends "activities/base.html" %}

{% block title %}Jahreszeit – {{ object.full_name }}{% endblock %}
{% block headline %}Jahreszeit: {{ object.full_name }}{% endblock %}

{% block content %}
<ul>
{% for object in object.activity_set.all %}
   <li><a href="{% url 'activities:activity-detail' object.id %}">{{ object.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/season_list.html
{% extends "activities/base.html" %}

{% block title %}Jahreszeiten{% endblock %}
{% block headline %}Jahreszeiten{% endblock %}

{% block content %}
<ul>
{% for object in object_list %}
   <li><a href="{% url 'activities:season-detail' object.name %}">{{ object.full_name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/tag_detail.html
{% extends "activities/base.html" %}

{% block title %}Tag – {{ object.name|capfirst }}{% endblock %}
{% block headline %}Tag: {{ object.name|capfirst }}{% endblock %}

{% block content %}
<ul>
{% for object in object.activity_set.all %}
   <li><a href="{% url 'activities:activity-detail' object.id %}">{{ object.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/activities/tag_list.html
{% extends "activities/base.html" %}

{% block title %}Tags{% endblock %}
{% block headline %}Tags{% endblock %}

{% block content %}
<ul>
{% for object in object_list %}
   <li><a href="{% url 'activities:tag-detail' object.id %}">{{ object.name|capfirst }}</a></li>
{% endfor %}
</ul>
{% endblock %}